[project]
name = "expense-tracker-remote-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.1",
    "aiosqlite>=0.20.0",
    "python-dateutil>=2.8.2",
]
